export type CheatsheetItem = {
  id: string;
  title: string;
  contentType: 'shortcut' | 'command' | 'playbook';
  intentTags: string[];
  shortcut?: string;
  command?: string;
  description: string;
  examples: string[];
  relatedActions: string[];
  difficulty: 'beginner' | 'daily' | 'advanced';
  playbookSlug?: string;
  practicePath?: string;
};

export const CHEATSHEET_ITEMS: CheatsheetItem[] = [
  {
    id: 'cs-split-vertical',
    title: '패인 세로 분할',
    contentType: 'shortcut',
    intentTags: ['split', 'pane', 'vertical'],
    shortcut: 'Ctrl+b (prefix) + %',
    description: '현재 패인을 좌우로 분할합니다.',
    examples: ['로그와 쉘을 동시에 보기'],
    relatedActions: ['sim.pane.split.vertical'],
    difficulty: 'beginner',
    practicePath: '/practice?lesson=split-resize',
  },
  {
    id: 'cs-split-horizontal',
    title: '패인 가로 분할',
    contentType: 'shortcut',
    intentTags: ['split', 'pane', 'horizontal'],
    shortcut: 'Ctrl+b (prefix) + "',
    description: '현재 패인을 상하로 분할합니다.',
    examples: ['상단 빌드, 하단 로그'],
    relatedActions: ['sim.pane.split.horizontal'],
    difficulty: 'beginner',
    practicePath: '/practice?lesson=split-resize',
  },
  {
    id: 'cs-window-new',
    title: '새 윈도우 생성',
    contentType: 'shortcut',
    intentTags: ['window', 'new'],
    shortcut: 'Ctrl+b (prefix) + c',
    description: '새 tmux window를 생성합니다.',
    examples: ['서비스별 window 분리'],
    relatedActions: ['sim.window.new'],
    difficulty: 'beginner',
    practicePath: '/practice?lesson=basics',
  },
  {
    id: 'cs-window-next',
    title: '다음 윈도우 이동',
    contentType: 'shortcut',
    intentTags: ['window', 'next', 'navigation'],
    shortcut: 'Ctrl+b (prefix) + n',
    description: '다음 window로 이동합니다.',
    examples: ['모니터링 window 순환'],
    relatedActions: ['sim.window.next'],
    difficulty: 'daily',
    practicePath: '/practice?lesson=pane-focus-flow',
  },
  {
    id: 'cs-copy-mode',
    title: 'copy-mode 진입',
    contentType: 'shortcut',
    intentTags: ['copy-mode', 'search'],
    shortcut: 'Ctrl+b (prefix) + [',
    description: '스크롤/검색/선택 복사를 위한 copy-mode로 들어갑니다.',
    examples: ['로그 검색 후 복사'],
    relatedActions: ['sim.copymode.enter'],
    difficulty: 'advanced',
    practicePath: '/practice?lesson=copy-search',
  },
  {
    id: 'cs-command-mode',
    title: 'command mode 진입',
    contentType: 'shortcut',
    intentTags: ['command', 'colon'],
    shortcut: 'Ctrl+b (prefix) + :',
    description: 'tmux 명령을 직접 실행합니다.',
    examples: ['new-window', 'split-window -h'],
    relatedActions: ['sim.command.execute'],
    difficulty: 'advanced',
    practicePath: '/practice?lesson=command-subset',
  },
  {
    id: 'cs-session-main',
    title: '세션 유지 시작',
    contentType: 'command',
    intentTags: ['session', 'persistent-session', 'detach-attach'],
    command: 'tmux new -As main',
    description: '세션이 없으면 생성, 있으면 재사용합니다.',
    examples: ['원격 서버 접속 직후 실행'],
    relatedActions: ['sim.session.new'],
    difficulty: 'daily',
    practicePath: '/practice?lesson=attach-detach',
  },
  {
    id: 'cs-detach',
    title: '세션 분리(detach)',
    contentType: 'shortcut',
    intentTags: ['detach', 'session', 'reconnect'],
    shortcut: 'Ctrl+b (prefix) + d',
    description: '현재 세션은 유지한 채 클라이언트만 분리합니다.',
    examples: ['SSH를 끊기 전에 안전하게 이탈'],
    relatedActions: ['sim.session.detach'],
    difficulty: 'daily',
    practicePath: '/practice?lesson=attach-detach-shortcuts',
  },
  {
    id: 'cs-attach-main',
    title: '기준 세션 재접속',
    contentType: 'command',
    intentTags: ['attach', 'session', 'main'],
    command: 'tmux attach -t main',
    description: '고정한 main 세션으로 다시 붙습니다.',
    examples: ['점심 후 작업 복구'],
    relatedActions: ['sim.session.attach'],
    difficulty: 'daily',
    practicePath: '/practice?lesson=attach-detach',
  },
  {
    id: 'cs-layout-tiled',
    title: '레이아웃 균등 정렬',
    contentType: 'command',
    intentTags: ['layout', 'tiled', 'pane'],
    command: 'tmux select-layout tiled',
    description: '분할된 패인을 균등한 그리드로 정렬합니다.',
    examples: ['레이아웃이 무너졌을 때 즉시 복구'],
    relatedActions: ['sim.layout.tiled'],
    difficulty: 'daily',
    practicePath: '/practice?lesson=layout-craft',
  },
  {
    id: 'cs-list-panes',
    title: '전체 패인 상태 확인',
    contentType: 'command',
    intentTags: ['list', 'panes', 'status'],
    command: "tmux list-panes -a -F '#S:#I.#P #{pane_current_command}'",
    description: '세션/윈도우/패인별 현재 명령을 한 번에 확인합니다.',
    examples: ['병렬 작업 상태 점검'],
    relatedActions: ['sim.pane.inspect'],
    difficulty: 'advanced',
    practicePath: '/practice?lesson=workspace-compose',
  },
  {
    id: 'cs-capture-pane-tail',
    title: '패인 출력 마지막 50줄 추출',
    contentType: 'command',
    intentTags: ['capture-pane', 'logs', 'tail'],
    command: 'tmux capture-pane -t dev-server -p | tail -50',
    description: '실행 중 세션에 붙지 않고 최근 로그만 확인합니다.',
    examples: ['dev 서버 상태 확인'],
    relatedActions: ['sim.command.capture-pane'],
    difficulty: 'advanced',
    practicePath: '/practice?lesson=command-subset',
  },
  {
    id: 'cs-escape-time',
    title: '입력 지연 완화',
    contentType: 'command',
    intentTags: ['escape-time', 'latency', 'keys'],
    command: 'tmux set -sg escape-time 10',
    description: 'prefix 이후 키 입력 지연을 줄이는 기본 값입니다.',
    examples: ['중첩 tmux에서 키 반응 점검'],
    relatedActions: ['sim.keys.escape-time'],
    difficulty: 'advanced',
    practicePath: '/practice?lesson=command-subset-shortcuts',
  },
  {
    id: 'cs-recommended-config',
    title: '권장 tmux.conf',
    contentType: 'playbook',
    intentTags: ['tmux.conf', 'config', 'recommended'],
    description: 'mouse/base-index/mode-keys/리로드 바인딩까지 포함한 팀 공통 베이스 설정입니다.',
    examples: ['set -g mouse on', 'setw -g mode-keys vi', 'bind r source-file ~/.tmux.conf'],
    relatedActions: ['sim.config.apply'],
    difficulty: 'daily',
    playbookSlug: 'recommended-config',
    practicePath: '/practice?lesson=command-subset',
  },
  {
    id: 'cs-session-persistence',
    title: '세션 유지 플레이북',
    contentType: 'playbook',
    intentTags: ['keep session alive', 'persistent-session', 'detach-attach'],
    description: 'detach/attach 루틴으로 작업 컨텍스트를 유지합니다.',
    examples: ['tmux ls', 'tmux attach -t main'],
    relatedActions: ['sim.session.new', 'sim.window.next'],
    difficulty: 'daily',
    playbookSlug: 'session-persistence',
    practicePath: '/practice?lesson=attach-detach',
  },
  {
    id: 'cs-tailscale-ssh',
    title: 'Tailscale SSH 원격',
    contentType: 'playbook',
    intentTags: ['tailscale', 'remote-ssh', 'secure-remote'],
    description: 'Tailscale SSH로 안전하게 접속해 tmux 세션(work)을 끊김 없이 복구하는 원격 운영 절차입니다.',
    examples: ['sudo tailscale set --ssh', 'tailscale ssh user@host "tmux new -As work"'],
    relatedActions: ['sim.command.shell', 'sim.session.new'],
    difficulty: 'advanced',
    playbookSlug: 'tailscale-ssh-workflow',
    practicePath: '/practice?lesson=attach-detach',
  },
  {
    id: 'cs-code-log-3pane-loop',
    title: '코드·테스트·로그 3패인',
    contentType: 'playbook',
    intentTags: ['layout', 'workflow', '3pane'],
    description: '코드/테스트/로그를 같은 윈도우에서 고정하는 운영 루틴입니다.',
    examples: ['split-window', 'select-layout tiled'],
    relatedActions: ['sim.layout.compose'],
    difficulty: 'daily',
    playbookSlug: 'code-log-3pane-loop',
    practicePath: '/practice?lesson=layout-craft',
  },
  {
    id: 'cs-scrollback-clipboard-osc52',
    title: '로그 검색 후 클립보드 복사',
    contentType: 'playbook',
    intentTags: ['copy-mode', 'clipboard', 'osc52'],
    description: '검색-복사-클립보드 전달까지 한 번에 점검하는 루틴입니다.',
    examples: ['show -g set-clipboard', 'save-buffer'],
    relatedActions: ['sim.copymode.copy'],
    difficulty: 'advanced',
    playbookSlug: 'scrollback-clipboard-osc52',
    practicePath: '/practice?lesson=copy-search',
  },
  {
    id: 'cs-key-input-troubleshooting',
    title: '키 입력 지연/충돌 점검',
    contentType: 'playbook',
    intentTags: ['keys', 'prefix', 'escape-time', 'troubleshooting'],
    description: 'prefix, escape-time, 중첩 전달까지 빠르게 점검합니다.',
    examples: ['show -g prefix', 'set -sg escape-time 10'],
    relatedActions: ['sim.keys.troubleshoot'],
    difficulty: 'advanced',
    playbookSlug: 'key-input-troubleshooting',
    practicePath: '/practice?lesson=command-subset-shortcuts',
  },
  {
    id: 'cs-terminal-render-troubleshooting',
    title: '터미널 렌더/색상 깨짐 점검',
    contentType: 'playbook',
    intentTags: ['terminal', 'render', 'color', 'troubleshooting'],
    description: 'TERM, 상태줄, 렌더 꼬임을 짧은 순서로 점검합니다.',
    examples: ['echo $TERM', 'refresh-client -S'],
    relatedActions: ['sim.terminal.troubleshoot'],
    difficulty: 'advanced',
    playbookSlug: 'terminal-render-troubleshooting',
    practicePath: '/practice?lesson=command-subset',
  },
  {
    id: 'cs-claude-worktree-sessions',
    title: 'Claude Code 병렬 작업 분리',
    contentType: 'playbook',
    intentTags: ['claude code', 'worktree', 'parallel', 'session'],
    description: 'worktree와 tmux 세션을 1:1로 매핑해 충돌을 줄입니다.',
    examples: ['git worktree add', 'tmux new -s agent-auth -c ...'],
    relatedActions: ['sim.agent.parallel'],
    difficulty: 'advanced',
    playbookSlug: 'claude-worktree-sessions',
    practicePath: '/practice?lesson=workspace-compose',
  },
  {
    id: 'cs-claude-dev-server-split',
    title: 'Claude Code dev 서버 분리',
    contentType: 'playbook',
    intentTags: ['claude code', 'dev server', 'capture-pane'],
    description: '대화 세션과 long-running 서버를 분리해 운영합니다.',
    examples: ['new-session -d', 'capture-pane -p | tail -50'],
    relatedActions: ['sim.agent.devserver'],
    difficulty: 'advanced',
    playbookSlug: 'claude-dev-server-split',
    practicePath: '/practice?lesson=command-subset',
  },
  {
    id: 'cs-agent-teams-tmux-mode',
    title: 'Agent Teams tmux 모드 점검',
    contentType: 'playbook',
    intentTags: ['agent teams', 'tmux mode', 'send-keys'],
    description: '패인 분할 실행과 send-keys 경합 포인트를 점검합니다.',
    examples: ['echo $TMUX', 'list-panes -a'],
    relatedActions: ['sim.agent.teams'],
    difficulty: 'advanced',
    playbookSlug: 'agent-teams-tmux-mode',
    practicePath: '/practice?lesson=workspace-compose-shortcuts',
  },
];
