export type CheatsheetItem = {
    id: string;
    title: string;
    contentType: 'shortcut' | 'command' | 'playbook';
    intentTags: string[];
    shortcut?: string;
    command?: string;
    description: string;
    examples: string[];
    relatedActions: string[];
    difficulty: 'beginner' | 'daily' | 'advanced';
    playbookSlug?: string;
    practicePath?: string;
};
export const CHEATSHEET_ITEMS: CheatsheetItem[] = [
    {
        id: 'cs-split-vertical',
        title: __tx("\uD328\uC778 \uC138\uB85C \uBD84\uD560"),
        contentType: 'shortcut',
        intentTags: ['split', 'pane', 'vertical'],
        shortcut: 'Ctrl+b (prefix) + %',
        description: __tx("\uD604\uC7AC \uD328\uC778\uC744 \uC88C\uC6B0\uB85C \uBD84\uD560\uD569\uB2C8\uB2E4."),
        examples: [__tx("\uB85C\uADF8\uC640 \uC258\uC744 \uB3D9\uC2DC\uC5D0 \uBCF4\uAE30")],
        relatedActions: ['sim.pane.split.vertical'],
        difficulty: 'beginner',
        practicePath: '/practice?lesson=split-resize',
    },
    {
        id: 'cs-split-horizontal',
        title: __tx("\uD328\uC778 \uAC00\uB85C \uBD84\uD560"),
        contentType: 'shortcut',
        intentTags: ['split', 'pane', 'horizontal'],
        shortcut: 'Ctrl+b (prefix) + "',
        description: __tx("\uD604\uC7AC \uD328\uC778\uC744 \uC0C1\uD558\uB85C \uBD84\uD560\uD569\uB2C8\uB2E4."),
        examples: [__tx("\uC0C1\uB2E8 \uBE4C\uB4DC, \uD558\uB2E8 \uB85C\uADF8")],
        relatedActions: ['sim.pane.split.horizontal'],
        difficulty: 'beginner',
        practicePath: '/practice?lesson=split-resize',
    },
    {
        id: 'cs-window-new',
        title: __tx("\uC0C8 \uC708\uB3C4\uC6B0 \uC0DD\uC131"),
        contentType: 'shortcut',
        intentTags: ['window', 'new'],
        shortcut: 'Ctrl+b (prefix) + c',
        description: __tx("\uC0C8 tmux window\uB97C \uC0DD\uC131\uD569\uB2C8\uB2E4."),
        examples: [__tx("\uC11C\uBE44\uC2A4\uBCC4 window \uBD84\uB9AC")],
        relatedActions: ['sim.window.new'],
        difficulty: 'beginner',
        practicePath: '/practice?lesson=basics',
    },
    {
        id: 'cs-window-next',
        title: __tx("\uB2E4\uC74C \uC708\uB3C4\uC6B0 \uC774\uB3D9"),
        contentType: 'shortcut',
        intentTags: ['window', 'next', 'navigation'],
        shortcut: 'Ctrl+b (prefix) + n',
        description: __tx("\uB2E4\uC74C window\uB85C \uC774\uB3D9\uD569\uB2C8\uB2E4."),
        examples: [__tx("\uBAA8\uB2C8\uD130\uB9C1 window \uC21C\uD658")],
        relatedActions: ['sim.window.next'],
        difficulty: 'daily',
        practicePath: '/practice?lesson=pane-focus-flow',
    },
    {
        id: 'cs-copy-mode',
        title: __tx("copy-mode \uC9C4\uC785"),
        contentType: 'shortcut',
        intentTags: ['copy-mode', 'search'],
        shortcut: 'Ctrl+b (prefix) + [',
        description: __tx("\uC2A4\uD06C\uB864/\uAC80\uC0C9/\uC120\uD0DD \uBCF5\uC0AC\uB97C \uC704\uD55C copy-mode\uB85C \uB4E4\uC5B4\uAC11\uB2C8\uB2E4."),
        examples: [__tx("\uB85C\uADF8 \uAC80\uC0C9 \uD6C4 \uBCF5\uC0AC")],
        relatedActions: ['sim.copymode.enter'],
        difficulty: 'advanced',
        practicePath: '/practice?lesson=copy-search',
    },
    {
        id: 'cs-command-mode',
        title: __tx("command mode \uC9C4\uC785"),
        contentType: 'shortcut',
        intentTags: ['command', 'colon'],
        shortcut: 'Ctrl+b (prefix) + :',
        description: __tx("tmux \uBA85\uB839\uC744 \uC9C1\uC811 \uC2E4\uD589\uD569\uB2C8\uB2E4."),
        examples: ['new-window', 'split-window -h'],
        relatedActions: ['sim.command.execute'],
        difficulty: 'advanced',
        practicePath: '/practice?lesson=command-subset',
    },
    {
        id: 'cs-session-main',
        title: __tx("\uC138\uC158 \uC720\uC9C0 \uC2DC\uC791"),
        contentType: 'command',
        intentTags: ['session', 'persistent-session', 'detach-attach'],
        command: 'tmux new -As main',
        description: __tx("\uC138\uC158\uC774 \uC5C6\uC73C\uBA74 \uC0DD\uC131, \uC788\uC73C\uBA74 \uC7AC\uC0AC\uC6A9\uD569\uB2C8\uB2E4."),
        examples: [__tx("\uC6D0\uACA9 \uC11C\uBC84 \uC811\uC18D \uC9C1\uD6C4 \uC2E4\uD589")],
        relatedActions: ['sim.session.new'],
        difficulty: 'daily',
        practicePath: '/practice?lesson=attach-detach',
    },
    {
        id: 'cs-recommended-config',
        title: __tx("\uAD8C\uC7A5 tmux.conf"),
        contentType: 'playbook',
        intentTags: ['tmux.conf', 'config', 'recommended'],
        description: __tx("mouse/base-index/mode-keys/\uB9AC\uB85C\uB4DC \uBC14\uC778\uB529\uAE4C\uC9C0 \uD3EC\uD568\uD55C \uD300 \uACF5\uD1B5 \uBCA0\uC774\uC2A4 \uC124\uC815\uC785\uB2C8\uB2E4."),
        examples: ['set -g mouse on', 'setw -g mode-keys vi', 'bind r source-file ~/.tmux.conf'],
        relatedActions: ['sim.config.apply'],
        difficulty: 'daily',
        playbookSlug: 'recommended-config',
        practicePath: '/practice?lesson=command-subset',
    },
    {
        id: 'cs-session-persistence',
        title: __tx("\uC138\uC158 \uC720\uC9C0 \uD50C\uB808\uC774\uBD81"),
        contentType: 'playbook',
        intentTags: ['keep session alive', 'persistent-session', 'detach-attach'],
        description: __tx("detach/attach \uB8E8\uD2F4\uC73C\uB85C \uC791\uC5C5 \uCEE8\uD14D\uC2A4\uD2B8\uB97C \uC720\uC9C0\uD569\uB2C8\uB2E4."),
        examples: ['tmux ls', 'tmux attach -t main'],
        relatedActions: ['sim.session.new', 'sim.window.next'],
        difficulty: 'daily',
        playbookSlug: 'session-persistence',
        practicePath: '/practice?lesson=attach-detach',
    },
    {
        id: 'cs-tailscale-ssh',
        title: __tx("Tailscale SSH \uC6D0\uACA9"),
        contentType: 'playbook',
        intentTags: ['tailscale', 'remote-ssh', 'secure-remote'],
        description: __tx("Tailscale SSH\uB85C \uC548\uC804\uD558\uAC8C \uC811\uC18D\uD574 tmux \uC138\uC158(work)\uC744 \uB04A\uAE40 \uC5C6\uC774 \uBCF5\uAD6C\uD558\uB294 \uC6D0\uACA9 \uC6B4\uC601 \uC808\uCC28\uC785\uB2C8\uB2E4."),
        examples: ['sudo tailscale set --ssh', 'tailscale ssh user@host "tmux new -As work"'],
        relatedActions: ['sim.command.shell', 'sim.session.new'],
        difficulty: 'advanced',
        playbookSlug: 'tailscale-ssh-workflow',
        practicePath: '/practice?lesson=attach-detach',
    },
];
